import type {Metadata} from 'next';

export const metadata: Metadata = {
    title: 'Regístrate',
    description: 'Generated by create next app',
};

export default function RegistroLayout({children}: { children: React.ReactNode }) {
    return (
        <>
            {children}
        </>
    );
}